"use client";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
const fmt=(n:number)=>n.toLocaleString("fr-FR",{style:"currency",currency:"USD",maximumFractionDigits:0});
const ZONES=[{nom:"Paleto",bonus:"Nord +1%",drogue:"Mexicana"},{nom:"Sandy Shores",bonus:"Nord +4%",drogue:"Meth Bleue"},{nom:"Grapeseed",bonus:"Nord +1%",drogue:"Mexicana"},{nom:"Vinewood",bonus:"10%",drogue:"Tranq"},{nom:"Aéroport",bonus:"4%",drogue:"Meth Bleue"},{nom:"Wardog",bonus:"1%",drogue:"Mexicana"},{nom:"Mirror Park",bonus:"0%",drogue:""},{nom:"Fête Foraine",bonus:"0%",drogue:"Meth Bleue"},{nom:"Barillo Plage",bonus:"7%",drogue:"Tranq"},{nom:"Del Perro",bonus:"10%",drogue:"Weed"},{nom:"Roxwood Est",bonus:"Nord +10%",drogue:"Crack"},{nom:"Eclypse Tower",bonus:"10%",drogue:""},{nom:"Vespucci",bonus:"4%",drogue:"Meth Bleue"},{nom:"Roxwood Ouest",bonus:"Nord +7%",drogue:"Mexicana"},{nom:"Terrain de cross",bonus:"Nord +10%",drogue:"Mexicana"},{nom:"Champ éolienne",bonus:"Nord +0%",drogue:""},{nom:"CAYO Perico",bonus:"10%",drogue:"Cocaïne"}];
const DROGUES=[{nom:"Cocaïne",emoji:"❄️",min:429,max:449,sem:17},{nom:"Tranq",emoji:"💉",min:275,max:290,sem:0},{nom:"Meth Bleue",emoji:"🔵",min:289,max:309,sem:4},{nom:"Weed",emoji:"🌿",min:442,max:464,sem:13},{nom:"Purple",emoji:"🟣",min:322,max:344,sem:1},{nom:"Crack",emoji:"💎",min:339,max:359,sem:9},{nom:"Mexicana",emoji:"🌶️",min:359,max:379,sem:11},{nom:"Ecstasy",emoji:"💊",min:180,max:300,sem:0},{nom:"Lean",emoji:"🥤",min:300,max:350,sem:0},{nom:"B-Magic",emoji:"✨",min:450,max:470,sem:0}];
const ACCS=[{nom:"Chargeurs Pistolets",prix:225000},{nom:"Chargeurs Auto",prix:500000},{nom:"Chargeurs Lourdes",prix:750000},{nom:"Silencieux Pistolets",prix:17500},{nom:"Silencieux Auto",prix:25000},{nom:"Silencieux Lourdes",prix:30000},{nom:"Viseurs Pistolets",prix:17500},{nom:"Viseurs Auto",prix:25000},{nom:"Viseurs Lourdes",prix:30000},{nom:"Poignées Lourdes",prix:30000},{nom:"Lampes Pistolets",prix:17500},{nom:"Lampes Lourdes",prix:30000},{nom:"Compensateurs Pistolets",prix:17500},{nom:"Freins Auto",prix:25000},{nom:"Freins Lourdes",prix:30000},{nom:"Canons Auto",prix:25000},{nom:"Canons Lourdes",prix:30000}];
export default function PrixPage() {
  const [tab,setTab]=useState<"drogues"|"accessoires"|"zones"|"custom">("drogues");
  const [custom,setCustom]=useState<any[]>([]);
  const [form,setForm]=useState({nom:"",categorie:"arme",emoji:"📦",prix_min:0,prix_max:0,prix_achat:0,vendeur:"",notes:""});
  const [showForm,setShowForm]=useState(false);
  const [saving,setSaving]=useState(false);
  const [toast,setToast]=useState<string|null>(null);
  useEffect(()=>{if(supabase)supabase.from("obsidian_prix").select("*").order("ordre").then(({data})=>setCustom(data||[]));},[]);
  function showT(m:string){setToast(m);setTimeout(()=>setToast(null),3000);}
  async function save(){if(!supabase||!form.nom)return;setSaving(true);const{data}=await supabase.from("obsidian_prix").insert([{...form,actif:true,ordre:custom.length+1}]).select().single();if(data)setCustom(c=>[...c,data]);setShowForm(false);setForm({nom:"",categorie:"arme",emoji:"📦",prix_min:0,prix_max:0,prix_achat:0,vendeur:"",notes:""});showT("Ajouté");setSaving(false);}
  async function del(id:string){if(!supabase)return;await supabase.from("obsidian_prix").delete().eq("id",id);setCustom(c=>c.filter(x=>x.id!==id));}
  return (
    <div className="page-container">
      <a className="back-link" href="/obsidian">← Dashboard Obsidian</a>
      <div className="page-header"><div><h1 className="page-title">💲 Tableau des prix</h1><p className="page-subtitle">Drogues · Accessoires · Zones · Personnalisé</p><div className="gold-line"/></div><button className="btn btn-gold" onClick={()=>setShowForm(true)}>+ Ajouter</button></div>
      <div style={{display:"flex",gap:"0.5rem",marginBottom:"1.25rem",flexWrap:"wrap"}}>
        {[["drogues","💊 Drogues"],["accessoires","🔧 Accessoires"],["zones","🗺️ Zones"],["custom","📋 Personnalisé"]].map(([k,l])=><button key={k} onClick={()=>setTab(k as any)} style={{padding:"0.5rem 1rem",borderRadius:"var(--radius)",cursor:"pointer",fontFamily:"'Inter',sans-serif",fontSize:"0.82rem",fontWeight:tab===k?700:400,background:tab===k?"var(--gold-muted)":"var(--surface)",border:`1px solid ${tab===k?"rgba(201,168,76,0.4)":"var(--border)"}`,color:tab===k?"var(--gold)":"var(--text-muted)"}}>{l}</button>)}
      </div>
      {tab==="drogues"&&<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(220px,1fr))",gap:"0.75rem"}}>{DROGUES.map(d=><div key={d.nom} className="card"><div style={{display:"flex",alignItems:"center",gap:"0.5rem",marginBottom:"0.625rem"}}><span style={{fontSize:"1.3rem"}}>{d.emoji}</span><div><div style={{fontWeight:700}}>{d.nom}</div><div style={{fontSize:"0.65rem",color:"var(--success)"}}>+{d.sem} sem.</div></div></div><div style={{fontFamily:"'Playfair Display',serif",fontWeight:900,color:"var(--gold)"}}>{fmt(d.min)} – {fmt(d.max)}</div><div style={{fontSize:"0.62rem",color:"var(--text-dim)"}}>par unité</div></div>)}</div>}
      {tab==="accessoires"&&<div style={{display:"flex",flexDirection:"column",gap:"0.375rem"}}>{ACCS.map(a=><div key={a.nom} style={{display:"flex",justifyContent:"space-between",padding:"0.625rem 1rem",background:"var(--card)",borderRadius:"var(--radius)",border:"1px solid var(--border)"}}><span style={{fontWeight:500}}>{a.nom}</span><span style={{fontWeight:700,color:"var(--gold)"}}>{fmt(a.prix)}</span></div>)}</div>}
      {tab==="zones"&&<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(180px,1fr))",gap:"0.625rem"}}>{ZONES.map(z=><div key={z.nom} className="card"><div style={{fontWeight:700,marginBottom:"0.2rem"}}>{z.nom}</div><div style={{fontSize:"0.72rem",color:"var(--success)",fontWeight:600}}>+{z.bonus}</div>{z.drogue&&<div style={{fontSize:"0.68rem",color:"#7c3aed"}}>💊 {z.drogue}</div>}</div>)}</div>}
      {tab==="custom"&&<div style={{display:"flex",flexDirection:"column",gap:"0.4rem"}}>{custom.length===0?<div className="empty-state"><div className="empty-icon">📋</div><div className="empty-title">Aucun article</div></div>:custom.map(a=><div key={a.id} style={{display:"flex",alignItems:"center",gap:"1rem",padding:"0.75rem 1rem",background:"var(--card)",borderRadius:"var(--radius-lg)",border:"1px solid var(--border)"}}><span style={{fontSize:"1.2rem"}}>{a.emoji}</span><div style={{flex:1}}><div style={{fontWeight:600}}>{a.nom} <span style={{fontSize:"0.62rem",color:"var(--text-dim)"}}>{a.categorie}</span></div>{a.vendeur&&<div style={{fontSize:"0.65rem",color:"var(--text-dim)"}}>📍 {a.vendeur}</div>}</div>{(a.prix_min||a.prix_max)>0&&<div style={{fontWeight:700,color:"var(--gold)"}}>{fmt(a.prix_min||a.prix_max)}</div>}<button className="btn btn-ghost btn-sm" onClick={()=>del(a.id)} style={{color:"var(--danger)"}}>🗑️</button></div>)}</div>}
      {showForm&&<div className="modal-overlay" onClick={e=>e.target===e.currentTarget&&setShowForm(false)}><div className="modal"><div className="modal-header"><h2 className="modal-title">Ajouter article</h2><button className="modal-close" onClick={()=>setShowForm(false)}>×</button></div><div className="modal-body"><div className="form-grid"><div className="form-group"><label>Emoji</label><input value={form.emoji} onChange={e=>setForm(f=>({...f,emoji:e.target.value}))} style={{width:70}}/></div><div className="form-group"><label>Nom *</label><input autoFocus value={form.nom} onChange={e=>setForm(f=>({...f,nom:e.target.value}))}/></div><div className="form-group"><label>Catégorie</label><select value={form.categorie} onChange={e=>setForm(f=>({...f,categorie:e.target.value}))}>{["drogue","arme","accessoire","composant","autre"].map(c=><option key={c}>{c}</option>)}</select></div><div className="form-group"><label>Prix min ($)</label><input type="number" value={form.prix_min||""} onChange={e=>setForm(f=>({...f,prix_min:+e.target.value}))}/></div><div className="form-group"><label>Prix max ($)</label><input type="number" value={form.prix_max||""} onChange={e=>setForm(f=>({...f,prix_max:+e.target.value}))}/></div><div className="form-group"><label>Prix achat ($)</label><input type="number" value={form.prix_achat||""} onChange={e=>setForm(f=>({...f,prix_achat:+e.target.value}))}/></div><div className="form-group"><label>Vendeur</label><input value={form.vendeur} onChange={e=>setForm(f=>({...f,vendeur:e.target.value}))}/></div></div><div className="form-group" style={{marginBottom:0}}><label>Notes</label><textarea rows={2} value={form.notes} onChange={e=>setForm(f=>({...f,notes:e.target.value}))}/></div></div><div className="modal-footer"><button className="btn btn-outline" onClick={()=>setShowForm(false)}>Annuler</button><button className="btn btn-gold" onClick={save} disabled={saving||!form.nom}>{saving?"…":"Ajouter"}</button></div></div></div>}
      {toast&&<div className="toast-container"><div className="toast toast-success">✅ {toast}</div></div>}
    </div>
  );
}